### ISSUE TITLE
Migrate `password` field from Identity to User

### ISSUE THREAD

**Issue by jtushman** [wecohere/graphql-rails-example#2]
Individuals likely should have a single password as opposed to a password per email address. Let's move the password field out of EmailAndPasswordIdentity and onto the user.

https://github.com/wecohere/graphql-rails-example/blob/ab31c1732153b50dc75969cebb3181000c1b8645/app/models/email_and_password_identity.rb#L5-L9

**Comment by jtushman** [comment]
hmmmm - I see that you have it on the identity.rb.  wonder if it makes more sense just here

**Comment by zspencer** [comment]
I think I want to pull this onto User, putting the `password` as a thing that matches on a per-email basis doesn't really make sense to me after sleeping on it.
