### ISSUE TITLE
Question:  why define all three of these relationships?

### ISSUE THREAD

**Issue by jtushman** [wecohere/graphql-rails-example#3]
Just curious ...

https://github.com/wecohere/graphql-rails-example/blob/ab31c1732153b50dc75969cebb3181000c1b8645/app/models/user.rb#L5-L7

vs just leverage the identities relationship. and maybe with custom scopes, in `indentity.rb`:

```
  scope :email, -> { where(type: :email_and_password)}
```

**Comment by zspencer** [comment]
I wanted methods that live on the user object itself; as well as to make sure when they're called they can rely on polymorphic class-level definitions, for instance, I could do something like`user.email_and_password_identities.confirmed` in this case if I had a `confirmed` scope on the EmailAndPassword` identity, whereas `user.identities.email_and_password.confirmed` would not work unless `confirmed` was attached to the Identity parent; despite confirmation being a thing that only email based identities would need.
