### ISSUE TITLE
wrong class defined? 

### ISSUE THREAD

**Issue by jtushman** [wecohere/graphql-rails-example#4]
https://github.com/wecohere/graphql-rails-example/blob/ab31c1732153b50dc75969cebb3181000c1b8645/app/graphql/types/email_and_password_identity.rb#L4

should this be `class EmailAndPasswordIdentity`  and how and why is this necessary in comparision with EmailAndPasswordIdentityInput

**Comment by zspencer** [comment]
Oops, yea didn't notice putting tat in multiple places.
