### ISSUE TITLE
Why is identity part of session?

### ISSUE THREAD

**Issue by jtushman** [wecohere/graphql-rails-example#6]
https://github.com/wecohere/graphql-rails-example/blob/ab31c1732153b50dc75969cebb3181000c1b8645/app/graphql/types/user_session.rb#L8

once we authenticate, we need the token, and to know the user.  But do we need to know how they authenticated?

**Comment by zspencer** [comment]
I don't think we really do, I was returning it as part of verifying the tests completed, but removing it from the session type is totally reasonable.
