### ISSUE TITLE
Implement Node interface on User

### ISSUE THREAD

**Issue by jtushman** [wecohere/graphql-rails-example#7]
https://github.com/wecohere/graphql-rails-example/blob/ab31c1732153b50dc75969cebb3181000c1b8645/app/graphql/types/user.rb#L4

per:   https://gist.github.com/swalkinshaw/3a33e2d292b60e68fcebe12b62bbb3e2#ids-and-the-node-interface

**Comment by zspencer** [comment]
More than likely, yes. I don't have . "Node" type yet, but this feels like it should do so.
